package com.engine.common.protocol;

import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DisplayName("Message Protocol Tests")
class MessageTest {

    @Nested
    @DisplayName("Builder Defaults")
    class BuilderDefaults {

        @Test
        @DisplayName("Builder creates message with auto-generated correlationId and timestamp")
        void test_WhenBuilderCreatesMessage_ThenCorrelationIdAndTimestampAreAutoGenerated() {
            Message message = new Message.Builder(MessageType.HEARTBEAT).build();

            assertAll("auto-generated fields",
                    () -> assertNotNull(message.getCorrelationId(), "correlationId should be auto-generated"),
                    () -> assertDoesNotThrow(() -> UUID.fromString(message.getCorrelationId()),
                            "correlationId should be a valid UUID"),
                    () -> assertTrue(message.getTimestamp() > 0, "timestamp should be set to current time"),
                    () -> assertEquals(MessageType.HEARTBEAT, message.getType())
            );
        }
    }

    @Nested
    @DisplayName("Builder Validation")
    class BuilderValidation {

        @Test
        @DisplayName("Builder throws exception when MessageType is null")
        void test_WhenMessageTypeIsNull_ThenBuilderThrows() {
            assertThrows(Exception.class, () -> new Message.Builder((MessageType) null).build(),
                    "Should throw when MessageType is null");
        }
    }

    @Nested
    @DisplayName("Payload Defensive Copy")
    class PayloadDefensiveCopy {

        @Test
        @DisplayName("getPayload returns a defensive copy — modifying returned array does not affect message")
        void test_WhenPayloadArrayIsModifiedExternally_ThenMessagePayloadRemainsUnchanged() {
            byte[] original = {10, 20, 30};
            Message message = new Message.Builder(MessageType.TASK_ASSIGN)
                    .payload(original)
                    .build();

            byte[] retrieved = message.getPayload();
            retrieved[0] = 99;

            assertArrayEquals(new byte[]{10, 20, 30}, message.getPayload(),
                    "Payload should not be affected by modifications to the returned array");
        }
    }

    @Nested
    @DisplayName("hasPayload")
    class HasPayload {

        @Test
        @DisplayName("hasPayload returns false when no payload is set (null)")
        void test_WhenPayloadIsNull_ThenHasPayloadReturnsFalse() {
            Message message = new Message.Builder(MessageType.HEARTBEAT).build();

            assertFalse(message.hasPayload(),
                    "hasPayload should return false when no payload is set");
        }

        @Test
        @DisplayName("hasPayload returns false when payload is empty byte array")
        void test_WhenPayloadIsEmpty_ThenHasPayloadReturnsFalse() {
            Message message = new Message.Builder(MessageType.HEARTBEAT)
                    .payload(new byte[0])
                    .build();

            assertFalse(message.hasPayload(),
                    "hasPayload should return false for an empty payload");
        }

        @Test
        @DisplayName("hasPayload returns true when payload has data")
        void test_WhenPayloadHasData_ThenHasPayloadReturnsTrue() {
            Message message = new Message.Builder(MessageType.TASK_ASSIGN)
                    .payload(new byte[]{1, 2, 3})
                    .build();

            assertTrue(message.hasPayload(),
                    "hasPayload should return true when payload contains data");
        }
    }

    @Nested
    @DisplayName("Equals and HashCode")
    class EqualsAndHashCode {

        @Test
        @DisplayName("Messages with same correlationId are equal and have same hashCode")
        void test_WhenMessagesHaveSameCorrelationId_ThenTheyAreEqual() {
            Message msg1 = new Message.Builder(MessageType.HEARTBEAT).build();
            String correlationId = msg1.getCorrelationId();

            // Build another message and then compare same instance to itself (correlationId is auto-generated)
            // Since we can't set correlationId directly, we test reflexive equality
            assertAll("equality",
                    () -> assertEquals(msg1, msg1, "Message should be equal to itself"),
                    () -> assertEquals(msg1.hashCode(), msg1.hashCode(), "Hash code should be consistent")
            );
        }

        @Test
        @DisplayName("Messages with different correlationIds are not equal")
        void test_WhenMessagesHaveDifferentCorrelationIds_ThenTheyAreNotEqual() {
            Message msg1 = new Message.Builder(MessageType.HEARTBEAT).build();
            Message msg2 = new Message.Builder(MessageType.HEARTBEAT).build();

            assertNotEquals(msg1, msg2,
                    "Messages with different auto-generated correlationIds should not be equal");
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("toString contains message type and correlationId")
        void test_WhenToStringCalled_ThenContainsTypeAndCorrelationId() {
            Message message = new Message.Builder(MessageType.HEARTBEAT).build();
            String str = message.toString();

            assertAll("toString content",
                    () -> assertTrue(str.contains("HEARTBEAT") || str.contains("heartbeat"),
                            "toString should contain the message type"),
                    () -> assertTrue(str.contains(message.getCorrelationId()),
                            "toString should contain the correlationId")
            );
        }
    }
}
